name: Build Anngular CI

on: #Triggers
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Node.js config
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Execute angular build
        run: ng build
        # run: ng build --configuration production
